/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as MixProjectIdRouteImport } from './routes/mix.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const MixProjectIdRoute = MixProjectIdRouteImport.update({
  id: '/mix/$projectId',
  path: '/mix/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/mix/$projectId': typeof MixProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/mix/$projectId': typeof MixProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/mix/$projectId': typeof MixProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extract' | '/mix/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extract' | '/mix/$projectId'
  id: '__root__' | '/' | '/extract' | '/mix/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtractRoute: typeof ExtractRoute
  MixProjectIdRoute: typeof MixProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix/$projectId': {
      id: '/mix/$projectId'
      path: '/mix/$projectId'
      fullPath: '/mix/$projectId'
      preLoaderRoute: typeof MixProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtractRoute: ExtractRoute,
  MixProjectIdRoute: MixProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
